- hosts: all
  tasks:

  - name: update required packages
    become: true
    block:
    - name: Remove network timeout
      ini_file:
        path: /usr/lib/systemd/system/NetworkManager-wait-online.service
        section: Service
        option: ExecStart
        value: /usr/bin/nm-online -s -q -t 120
      notify: reboot
    - name: disable proc-sys-fs-binfmt_misc.automount
      systemd:
        name: proc-sys-fs-binfmt_misc.automount
        enabled: false
        masked: true
        state: stopped
      notify: reboot
    - name: update installed packages
      yum:
        name: "*"
        state: latest
        update_cache: true
      notify: reboot
    - name: install additional packages
      yum:
        name: 
        - libguestfs-tools-c
        - avahi
        state: present
      notify: reboot
    - name: enable avahi
      systemd:
        name: avahi-daemon
        enabled: true
        state: started
    always:
    - meta: flush_handlers

  - become: true
    block:
    - name: install podman
      yum:
        name: podman
        state: latest
#      notify: restart podman
    - user:
        name: podman
        generate_ssh_key: true
        ssh_key_type: ed25519
        password: ""
    - authorized_key:
        user: podman
        key: https://github.com/tunnel49.keys

#    - name: enable podman
#      systemd:
#        name: podman
#        enabled: true
#    always:
#    - meta: flush_handlers
#    - name: start podman
#      systemd:
#        name: podman
#        state: started

  handlers:

  - name: reboot
    become: true
    reboot:
      test_command: |
        systemctl is-system-running

#   - name: restart podman
#     become: true
#     systemd:
#       name: podman
#       state: restarted
